%define _unpackaged_files_terminate_build 1
%define pname hypothesis-cats
%define pmname hypothesis_cats

Name:     python3-module-%pname
Version:  0.1.0
Release:  alt1

Summary:  Allows to classify values generated by a Hypothesis strategy
License:  GPL-2.0-or-later
Group:    Development/Python3
Url:      https://github.com/wolneykien/hypothesis-cats

Packager: Paul Wolneykien <manowar@altlinux.org>

Source:   %name-%version.tar

BuildArch: noarch
BuildRequires: rpm-build-python3 python3-module-setuptools
BuildRequires: python3-module-wheel
BuildRequires: python3-test pytest3
BuildRequires: python3-module-hypothesis

%description
Hypothesis extension which allows to classify values generated by a
Hypothesis strategy and then to make complex assertions based on the
categories that consist up the example data given to the test.

%prep
%setup

%build
%pyproject_build

%install
%pyproject_install

%files
%doc README.rst examples
%python3_sitelibdir/%pmname
%python3_sitelibdir/%pmname-%version.dist-info

%changelog
* Tue Jul 26 2022 Paul Wolneykien <manowar@altlinux.org> 0.1.0-alt1
- Initial version.
